### ISSUE TITLE
User is fixed to nobody

### ISSUE THREAD

**Issue by dwlnetnl** [JensErat/docker-tinc#1]
Thanks for the Dockerfile, it makes deployment very sweet.

I'm doing some routing so I need to manipulate the route tables for which is root access required. I see that tinc is running under user nobody. Is it possible to make it overwritable (via an env var for example)?

**Comment by JensErat** [comment]
If you use a derived Docker image, simply override the `CMD` line. You can also do so when using `docker run` or `docker-compose` by setting another command:

    docker run jenserat/tinc start -D

would run the image without switching to root, but I'd not recommend doing so. Depending on your needs, setting another entrypoint to apply the routing rules might be more reasonable, but detalis will heavily depend on your requirements.

**Comment by dwlnetnl** [comment]
Thanks!
