### ISSUE TITLE
Container stops immediately and no config files are created

### ISSUE THREAD

**Issue by zachthedev** [JensErat/docker-tinc#3]
As the title says. 
Running:
Docker version 18.09.2, build 6247962
Ubuntu 18.10
latest tinc dockerfile
All running in a vultr vps

I run this command:
```
docker run -d \
    --name tinc \
    --net=host \
    --device=/dev/net/tun \
    --cap-add NET_ADMIN \
    --volume /srv/tinc:/etc/tinc \
    jenserat/tinc start -D
```
as root and it creates the containers, but when doing `docker container ls --all`, they are all exited and have stop codes, tinc is '1'. And there is no form of any config created anywhere, I even created the `tinc` folder in `etc` and `chown`'ed it to no avail.

**Comment by zachthedev** [comment]
@JensErat Bump

**Comment by zachthedev** [comment]
@JensErat Bump

**Comment by zachthedev** [comment]
@JensErat Any comment on this? It has been almost 2 weeks.

**Comment by Zangoran** [comment]
@JensErat Any help to push me in the right direction? I really need this

**Comment by zachthedev** [comment]
Used this docker instead: https://hub.docker.com/r/byscontrol/tinc
